// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://actmvkaaqgwlyrscoqdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdG12a2FhcWd3bHlyc2NvcWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTk0MTAsImV4cCI6MjA2NzI5NTQxMH0.hvE_DO8Kqg0BM6qTkiGV4wn8kogde5tIYd-wFEXftmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});